version: '3.9'

services:
  jupyter:
    container_name: jupyter
    hostname: jupyter
    build:
      context: ./code
      dockerfile: Dockerfile
    ports:
      - "8888:8888"
    volumes:
      - ./code:/code/